id: I4A454AEB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T17:03:04+00:00'
last_modified: '2022-06-07T12:23:19.297449+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6654
  title: བརྒྱད་སྟོང་འགྲེལ་ཆེན་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4981':
      image_group_id: I3CN6656
      title: Volume 1 of 'phags pa brgyad stong pa'i 'grel chen mngon par rtogs pa'i
        rgyan gyi snang ba/
      total_pages: 540
      order: 1
      base_file: 4981.txt
    9E2C:
      image_group_id: I3CN6657
      title: Volume 2 of 'phags pa brgyad stong pa'i 'grel chen mngon par rtogs pa'i
        rgyan gyi snang ba/
      total_pages: 542
      order: 2
      base_file: 9E2C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
